owner: Fabrik19
repo: upptime

sites:
  - name: Fabrik19
    url: https://fabrik19.de/
  - name: Mobilitysuite
    url: https://mobilitysuite.de/
  - name: Portal
    url: https://portal.mobilitysuite.de/
  - name: Portal Core
    url: https://prod-portal-core.api.mobilitysuite.de/_health

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://github.com/Fabrik19/upptime/raw/refs/heads/master/assets/logo.svg
  name: Fabrik19
  introTitle: "**Upptime** System Monitoring"
  introMessage: System Status for Fabrik19.
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
